version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: splitmate-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: splitmate_db
      MYSQL_USER: splitmate_user
      MYSQL_PASSWORD: splitmate_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: splitmate-backend
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/splitmate_db
      SPRING_DATASOURCE_USERNAME: splitmate_user
      SPRING_DATASOURCE_PASSWORD: splitmate_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mysql_data:
